
project_id = "bmopoxksyvamiewogvrj"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://lovable.dev"]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[db]
enabled = true
port = 54322
shadow_port = 54320
major_version = 15

[functions]
enabled = true
port = 54321

[functions.create-external-job]
verify_jwt = true

[functions.validate-business]
verify_jwt = false

[functions.validate-product]
verify_jwt = false

[realtime]
enabled = true
port = 54323

[storage]
enabled = true
port = 54324

[edge_runtime]
enabled = true
port = 54325

[analytics]
enabled = false
port = 54327
vector_port = 54328
