// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bmopoxksyvamiewogvrj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJtb3BveGtzeXZhbWlld29ndnJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0ODgwODYsImV4cCI6MjA2NDA2NDA4Nn0.Ino_wm7nUx7aTZ5WamENnW79Qny6bhNokRIoZ2CBwX8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);